spring:
      application:
               name: poc-graphql-app
      data:
          mongodb:
            uri: mongodb://192.168.32.70,192.168.32.123/cars?waitQueueMultiple=10000000
           
      output:
          ansi:
            enabled: ALWAYS                           

server:
      port: 8080

populate:
      active: true
      
graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: true

      spring-graphql-common:
               clientMutationIdName: clientMutationId
               injectClientMutationId: true
               allowEmptyClientMutationId: false
               mutationInputArgumentName: input
               outputObjectNamePrefix: Payload
               inputObjectNamePrefix: Input
               schemaMutationObjectName: Mutation      

